- hosts: terraform-ansible
  tasks:
  - name: criando o arquivo
    copy:
      dest: /home/ubuntu/index.html
      content: <h1>Terraform Ansible 123</h1>
  - name: criando o servidor
    # shell: "nohup python3 -m http.server 8080 &"
    shell: "nohup busybox httpd -f -p 8080 &"